databases:
  - name: rosava_production
    databaseName: rosava_production
    user: rosava

services:
  - type: web
    name: rosava
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rosava_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false